[package]
org = "ballerinax"
name = "health.fhir.r5.international500"
version = "0.9.2"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R5", "health_fhir_r5_international500"]
export = ["health.fhir.r5.international500"]

