[package]
org = "ballerinax"
name = "health.fhir.r5.international500"
version = "1.0.0"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R5", "health_fhir_r5_international500"]
readme = "Package.md"

