[package]
org = "ballerinax"
name = "health.fhir.r5"
version = "0.9.3"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R5"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r5"
