[package]
org = "ballerinax"
name = "health.fhirr5"
version = "${project.version}"
distribution = "${ballerina.version}"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R5", "service"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r5"

[build-options]
observabilityIncluded = true

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerinax"
artifactId = "fhirr5-native"
version = "${project.version}"
path = "./fhirr5-native-${project.version}.jar"
